### ISSUE TITLE
Cannot analyze through docker desktop

### ISSUE THREAD

**Issue by jamie-at-arkifi** [wagoodman/dive#495]
**What happened**:

I'm trying to analyze a multi-gigabyte local image, and it's just failing with "could not find image config"

```
🐚 dive myapp:latest
Image Source: docker://myapp:latest
Fetching image... (this can take a while for large images)
cannot fetch image
could not find image config
```

```
🐚 dive build .
Building image...
[REDACTED, but apparently successful]

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/9k057vmr8hx8ldwxbgravqng5
cannot build image
could not find image config
```

**What you expected to happen**:

Analysis

**How to reproduce it (as minimally and precisely as possible)**:

Honestly, I'm not sure what's going on to begin narrowing it down. It's a 3+GB image and not published to a registry.

**Anything else we need to know?**:

Some kind of `--verbose` might make tracking this down easier.

Buildx is being used.

**Environment**:
- OS version: Mac OSX 14.0
- Docker version: Docker Desktop for Mac 4.26.1, Docker Engine 24.0.7

**Comment by jamie-at-arkifi** [comment]
I think this might be a docker desktop thing?

`dive python:3.11` doesn't work either.

Running through the container (instead of the brew version) has the same result in both cases.

**Comment by mark2185** [comment]
Could you please try building `dive` from source? Specifically PR #490.

**Comment by jamie-at-arkifi** [comment]
(Some build instructions would help a bunch.)

Does not seem to--built 326d463 and `~/src/dive/snapshot/dive_darwin_arm64/dive build .` seems to be doing the same thing.

**Comment by mark2185** [comment]
Download the fork, checkout the right branch from that fork and run `go run main.go python:3.11` from the root of the clone.

**Comment by jamie-at-arkifi** [comment]
```
jamie@Jamies-MacBook-Pro ~/src/dive 326d463 🐚 go run main.go python:3.11
Image Source: docker://python:3.11
Fetching image... (this can take a while for large images)
cannot fetch image
could not find image config
exit status 1
```

**Comment by mark2185** [comment]
> By "some build instructions would help", I mean "I spent ten minutes fumbling through the makefile and eventually figured it out, which is not a great experience."

Ah, sorry, thought it was aimed at me. I do agree with the sentiment, though.

If you're up for _diving_ deeper into the issue, I'd look at where is the socket for `docker-desktop` located, try running `docker context ls`, and pointing [the variable in docker_host_unix.go](https://github.com/rajiv-k/dive/blob/main/dive/image/docker/docker_host_unix.go#L6) to that.

If not, please let me know, will see what I can do.

**Comment by jamie-at-arkifi** [comment]
```
🐚 docker context list
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                     KUBERNETES ENDPOINT   ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock
desktop-linux *     moby                Docker Desktop                            unix:///Users/jamie/.docker/run/docker.sock
```

**Comment by mark2185** [comment]
Would you kindly try replacing that line in`docker_host_unix.go` with `unix:///Users/jamie/.docker/run/docker.sock` and try it with some image again?

**Comment by jamie-at-arkifi** [comment]
```
jamie@Jamies-MacBook-Pro ~/src/dive 326d463 🐚 git diff
diff --git a/dive/image/docker/docker_host_unix.go b/dive/image/docker/docker_host_unix.go
index 52dae70..c93781d 100644
--- a/dive/image/docker/docker_host_unix.go
+++ b/dive/image/docker/docker_host_unix.go
@@ -3,5 +3,5 @@
 package docker

 const (
-       defaultDockerHost = "unix:///var/run/docker.sock"
+       defaultDockerHost = "unix:///Users/jamie/.docker/run/docker.sock"
 )
jamie@Jamies-MacBook-Pro ~/src/dive 326d463 🐚 go run main.go python:3.11
Image Source: docker://python:3.11
Fetching image... (this can take a while for large images)
cannot fetch image
could not find image config
exit status 1
```

**Comment by mark2185** [comment]
Alright, thanks!

Until that's fixed I'd recommend saving the image to a file and then passing the archive to `dive`, should be an example under `--help`.

**Comment by rajiv-k** [comment]
FYI, you don't have to change the `defaultDockerHost`. You can just export `DOCKER_HOST` with the desired value. For example, `export DOCKER_HOST=unix:///Users/jamie/.docker/run/docker.sock` as a workaround until #490 is merged.

**Comment by mark2185** [comment]
@rajiv-k but if I'm reading it right, it's _not_ working even after changing the host socket.

**Comment by Yunsang-Jeong** [comment]
@mark2185 try like this :D
```bash
sudo ln -s /Users/yunsang/.docker/run/docker.sock /var/run/docker.sock
```

**Comment by manuel-koch** [comment]
I have the same problem and `sudo ln -s <MY_SOCK_PATH> /var/run/docker.sock` results in `ln: /var/run/docker.sock: File exists`.

**Comment by tko** [comment]
FWIW with Docker Desktop on Mac it's a symlink in `/var/run` 
```
lrwxr-xr-x  1 root  daemon  42 Feb 19 10:12 /var/run/docker.sock -> /Users/test/.docker/run/docker.sock
srwxr-xr-x  1 test  staff    0 Feb 20 20:44 /Users/test/.docker/run/docker.sock
```
overriding DOCKER_HOST doesn't seem to make any difference for me.

**Comment by davidbielik** [comment]
Fixed it by enabling this option in Docker Desktop (MacOS) in the "Advanced" tab:

## `Allow the default Docker socket to be used (requires password)`

<img width="1094" alt="image" src="https://github.com/user-attachments/assets/117b9f56-f677-4d21-9b81-69230362430d">

**Comment by xxnuo** [comment]
<img width="777" alt="image" src="https://github.com/user-attachments/assets/35d82454-f379-4034-b1ae-04276e5efe18">

Still happen

```bash
dive 032c52613401
Image Source: docker://032c52613401
Fetching image... (this can take a while for large images)
cannot fetch image
could not find 'blobs/sha256/0dd753b657c966f26a5151f899593efa1f2874d71fabcedff646ede0cb0d2c67' in parsed layers
```

**Comment by DeanAyalon** [comment]
@xxnuo have you tested it with #490 or #511 merged in?

**Comment by manuel-koch** [comment]
@xxnuo I had similar problems in the past after docker-desktop was upgraded.
Suddenly some applications/terminal-tools where unable to use docker (again).
I solved it be re-applying this setting (see above) by "uncheck -> apply -> check -> apply" these options in docker-desktop-setup dialog.
Afterwards the failing tools were able to use docker socket again.

**Comment by xxnuo** [comment]
> @xxnuo have you tested it with #490 or #511 merged in?

Not yet, I will try it, thank you



> @xxnuo I had similar problems in the past after docker-desktop was upgraded. Suddenly some applications/terminal-tools where unable to use docker (again). I solved it be re-applying this setting (see above) by "uncheck -> apply -> check -> apply" these options in docker-desktop-setup dialog. Afterwards the failing tools were able to use docker socket again.

Unfortunately this method doesn't work, it's very puzzling that there are indeed other software that don't work properly Docker Desktop

**Comment by msamsel** [comment]
I had a very similar error, however, I'm using "colima" instead of docker-desktop.
When I adjust `DOCKER_HOST` to the colima path, then it starts to work.
![image](https://github.com/user-attachments/assets/8590015e-bb5c-4430-8f30-25a550839a03)
